# -*- coding: utf-8 -*-
"""Credit Card Fraud Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1js-CioD1ltleKTkBQNJv7agx5dATrRgm
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import metrics
from matplotlib import gridspec

df=pd.read_csv("creditcard.csv")

df.head()

print(df.shape)
print(df.describe())

fraud=df[df['Class']==1]
valid=df[df['Class']==0]
print("Fraud Cases: {}".format(len(df[df['Class']==1])))
print("Valid Transactions: {}".format(len(df[df['Class']==0])))

print("Amount details of the fraudulent transaction")
fraud.Amount.describe()

print("details of valid Transaction")
valid.Amount.describe()

corrmat=df.corr()
fig=plt.figure(figsize=(8,5))
sns.heatmap(corrmat , vmax = .8, square = True)
plt.show()

from sklearn.preprocessing import StandardScaler
df["NormalizedAmount"]=StandardScaler().fit_transform(df["Amount"].values.reshape(-1,1))
df=df.drop(["Amount"],axis=1)

df.head()

df=df.drop(["Time"],axis=1)
df.head()

X,Y=df.iloc[:,0:-1],df["Class"]

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

X_train.shape

X_test.shape